# Generated by Django 4.2.7 on 2023-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_alter_spotifytoken_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=150),
        ),
    ]
