# Generated by Django 4.2.7 on 2023-11-10 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0004_vote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
