# Generated by Django 4.2.7 on 2023-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_room_current_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="current_song",
        ),
        migrations.AddField(
            model_name="room",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
