# Generated by Django 4.2.7 on 2023-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_room_current_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_playlist",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
